// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/order.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderCreateCommand struct {
	OrderId              string                          `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId           string                          `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status               string                          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            int64                           `protobuf:"varint,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	RestaurantId         string                          `protobuf:"bytes,5,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Amount               float32                         `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderItems           []*OrderCreateCommand_OrderItem `protobuf:"bytes,7,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *OrderCreateCommand) Reset()         { *m = OrderCreateCommand{} }
func (m *OrderCreateCommand) String() string { return proto.CompactTextString(m) }
func (*OrderCreateCommand) ProtoMessage()    {}
func (*OrderCreateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{0}
}

func (m *OrderCreateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreateCommand.Unmarshal(m, b)
}
func (m *OrderCreateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreateCommand.Marshal(b, m, deterministic)
}
func (m *OrderCreateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreateCommand.Merge(m, src)
}
func (m *OrderCreateCommand) XXX_Size() int {
	return xxx_messageInfo_OrderCreateCommand.Size(m)
}
func (m *OrderCreateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreateCommand proto.InternalMessageInfo

func (m *OrderCreateCommand) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCreateCommand) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *OrderCreateCommand) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderCreateCommand) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *OrderCreateCommand) GetRestaurantId() string {
	if m != nil {
		return m.RestaurantId
	}
	return ""
}

func (m *OrderCreateCommand) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderCreateCommand) GetOrderItems() []*OrderCreateCommand_OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type OrderCreateCommand_OrderItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCreateCommand_OrderItem) Reset()         { *m = OrderCreateCommand_OrderItem{} }
func (m *OrderCreateCommand_OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderCreateCommand_OrderItem) ProtoMessage()    {}
func (*OrderCreateCommand_OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{0, 0}
}

func (m *OrderCreateCommand_OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreateCommand_OrderItem.Unmarshal(m, b)
}
func (m *OrderCreateCommand_OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreateCommand_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderCreateCommand_OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreateCommand_OrderItem.Merge(m, src)
}
func (m *OrderCreateCommand_OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderCreateCommand_OrderItem.Size(m)
}
func (m *OrderCreateCommand_OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreateCommand_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreateCommand_OrderItem proto.InternalMessageInfo

func (m *OrderCreateCommand_OrderItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OrderCreateCommand_OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderCreateCommand_OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderCreateCommand_OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderPaymentDebitedCommand struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderPaymentDebitedCommand) Reset()         { *m = OrderPaymentDebitedCommand{} }
func (m *OrderPaymentDebitedCommand) String() string { return proto.CompactTextString(m) }
func (*OrderPaymentDebitedCommand) ProtoMessage()    {}
func (*OrderPaymentDebitedCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{1}
}

func (m *OrderPaymentDebitedCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderPaymentDebitedCommand.Unmarshal(m, b)
}
func (m *OrderPaymentDebitedCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderPaymentDebitedCommand.Marshal(b, m, deterministic)
}
func (m *OrderPaymentDebitedCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPaymentDebitedCommand.Merge(m, src)
}
func (m *OrderPaymentDebitedCommand) XXX_Size() int {
	return xxx_messageInfo_OrderPaymentDebitedCommand.Size(m)
}
func (m *OrderPaymentDebitedCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPaymentDebitedCommand.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPaymentDebitedCommand proto.InternalMessageInfo

func (m *OrderPaymentDebitedCommand) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderPaymentDebitedCommand) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *OrderPaymentDebitedCommand) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*OrderCreateCommand)(nil), "pb.OrderCreateCommand")
	proto.RegisterType((*OrderCreateCommand_OrderItem)(nil), "pb.OrderCreateCommand.OrderItem")
	proto.RegisterType((*OrderPaymentDebitedCommand)(nil), "pb.OrderPaymentDebitedCommand")
}

func init() { proto.RegisterFile("pb/order.proto", fileDescriptor_e4944acb1d14eb6b) }

var fileDescriptor_e4944acb1d14eb6b = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0xa4, 0xff, 0x72, 0x05, 0x06, 0x0f, 0x28, 0x54, 0x42, 0x44, 0x65, 0xc9, 0x54,
	0x24, 0x78, 0x02, 0x54, 0x96, 0x4e, 0xad, 0xf2, 0x02, 0x95, 0x13, 0xdf, 0x90, 0xc1, 0x76, 0xb0,
	0xcf, 0x43, 0x9f, 0x9c, 0x15, 0xf9, 0xea, 0x16, 0x24, 0x56, 0xb6, 0xfb, 0x7e, 0x5f, 0x72, 0xe7,
	0xef, 0x0e, 0xee, 0xc6, 0xee, 0xc5, 0x3a, 0x85, 0x6e, 0x33, 0x3a, 0x4b, 0x56, 0xe4, 0x63, 0xb7,
	0xfe, 0xca, 0x41, 0xec, 0x23, 0xdb, 0x3a, 0x94, 0x84, 0x5b, 0xab, 0xb5, 0x34, 0x4a, 0x3c, 0xc0,
	0x82, 0xbf, 0x3c, 0x0e, 0xaa, 0xca, 0xea, 0xac, 0x29, 0xdb, 0x39, 0xeb, 0x9d, 0x12, 0x4f, 0xb0,
	0xec, 0x83, 0x27, 0xab, 0xcf, 0x6e, 0xce, 0x2e, 0x5c, 0xd0, 0x4e, 0x89, 0x7b, 0x98, 0x79, 0x92,
	0x14, 0x7c, 0x55, 0xb0, 0x97, 0x94, 0x78, 0x04, 0xe8, 0x79, 0x88, 0x3a, 0x5a, 0x53, 0x4d, 0xea,
	0xac, 0x29, 0xda, 0x32, 0x91, 0xbd, 0x11, 0xcf, 0x70, 0xeb, 0xd0, 0x93, 0x0c, 0x4e, 0x1a, 0x8a,
	0x9d, 0xa7, 0xfc, 0xf7, 0xcd, 0x0f, 0x3c, 0xf7, 0x96, 0xda, 0x06, 0x43, 0xd5, 0xac, 0xce, 0x9a,
	0xbc, 0x4d, 0x4a, 0xbc, 0xc3, 0x32, 0xbd, 0x97, 0x50, 0xfb, 0x6a, 0x5e, 0x17, 0xcd, 0xf2, 0xb5,
	0xde, 0x8c, 0xdd, 0xe6, 0x6f, 0xb8, 0x33, 0xda, 0x11, 0xea, 0x16, 0xec, 0xa5, 0xf4, 0x2b, 0x03,
	0xe5, 0xd5, 0x10, 0x02, 0x26, 0xbd, 0x55, 0x98, 0xb2, 0x73, 0x1d, 0x99, 0x91, 0x1a, 0x53, 0x62,
	0xae, 0x63, 0xa6, 0x60, 0x06, 0x3a, 0x8e, 0x6e, 0xe8, 0x91, 0xf3, 0xe6, 0x6d, 0x19, 0xc9, 0x21,
	0x02, 0xb1, 0x82, 0xc5, 0x67, 0x90, 0x86, 0x06, 0x3a, 0x71, 0xe0, 0x69, 0x7b, 0xd5, 0xeb, 0x11,
	0x56, 0x3c, 0xef, 0x20, 0x4f, 0x1a, 0x0d, 0x7d, 0x60, 0x37, 0x10, 0xaa, 0x7f, 0x3a, 0x40, 0x5a,
	0x52, 0xf1, 0x7b, 0x49, 0xdd, 0x8c, 0xcf, 0xfe, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xad,
	0x6a, 0x82, 0x08, 0x02, 0x00, 0x00,
}
